insert into staff (`name`,age,gender,job,treatArea) values ("王小龙",18,0,0,1);
insert into staff (`name`,age,gender,job,treatArea) values ("王小虎",18,0,0,2);
insert into staff (`name`,age,gender,job,treatArea) values ("王小明",18,0,0,3);
insert into staff (`name`,age,gender,job,treatArea) values ("张小小",19,1,1,4);
insert into staff (`name`,age,gender,job,treatArea) values ("王小小",19,1,2,1);
insert into staff (`name`,age,gender,job,treatArea) values ("李小小",19,1,2,2);
insert into staff (`name`,age,gender,job,treatArea) values ("赵小小",19,1,2,3);
insert into bed (treatArea,roomID) values(1,1);
insert into bed (treatArea,roomID) values(1,1);
insert into bed (treatArea,roomID) values(1,1);
insert into bed (treatArea,roomID) values(1,1);
insert into bed (treatArea,roomID) values(1,2);
insert into bed (treatArea,roomID) values(1,2);
insert into bed (treatArea,roomID) values(1,2);
insert into bed (treatArea,roomID) values(1,2);
insert into bed (treatArea,roomID) values(1,3);
insert into bed (treatArea,roomID) values(1,3);
insert into bed (treatArea,roomID) values(1,3);
insert into bed (treatArea,roomID) values(1,3);
insert into bed (treatArea,roomID) values(2,1);
insert into bed (treatArea,roomID) values(2,1);
insert into bed (treatArea,roomID) values(2,2);
insert into bed (treatArea,roomID) values(2,2);
insert into bed (treatArea,roomID) values(2,3);
insert into bed (treatArea,roomID) values(2,3);
insert into bed (treatArea,roomID) values(3,1);
insert into bed (treatArea,roomID) values(3,2);
insert into bed (treatArea,roomID) values(3,3);